# tests/svy/estimation/test_rep_domain_df.py
"""Domain-level degrees of freedom for Taylor and replication CIs (issue #3).

Fixture ``test_data/rep_domain_df_jkn_20260724.csv``: 4 strata x 4 PSUs x 5 obs,
with the JKn replicate weights generated by R so both packages see the identical
weight matrix::

    des <- svydesign(ids=~psu_id, strata=~stratum, weights=~w, data=d, nest=TRUE)
    rep <- as.svrepdesign(des, type="JKn")

The domain (``dom == 1``) drops PSUs 3-4 of stratum 1 and PSUs 2-4 of stratum 4,
so it removes whole PSUs from the design — which is what makes a domain df differ
from the full-design df.

Two conventions are pinned here, and they are deliberately different:

* **Taylor** follows R exactly, including on domains. R's
  ``degf(subset(des, dom==1))`` is 7 where the full design has 12, and svy
  reproduces the resulting CI to 1e-8.

* **Replication** uses ``df = n_reps - 1``, independent of the data — so it does
  *not* shrink on a domain. This is a deliberate svy convention, not an
  oversight: when a file ships only replicate weights, with no strata/PSU
  identifiers, the true design df is unknown and ``n_reps - 1`` is the honest
  default. R instead reads ``qr(weights(design, "analysis"))$rank - 1`` off the
  weight matrix (12 full / 9 on this domain), which is why the svy-vs-R
  validation notes pass an explicit ``df`` to ``confint()`` on the R side.
  The point estimates and standard errors agree with R exactly either way; only
  the t-quantile differs.
"""

from pathlib import Path

import polars as pl
import pytest

from svy import Design, RepWeights, Sample, col


TOL = 1e-8
N_REPS = 16
RSCALES = tuple([0.75] * N_REPS)  # (n_h - 1) / n_h for 4 PSUs per stratum


@pytest.fixture
def jkn_data():
    path = Path(__file__).parents[2] / "test_data" / "rep_domain_df_jkn_20260724.csv"
    if not path.exists():
        pytest.skip("Fixture rep_domain_df_jkn_20260724.csv not found")
    return pl.read_csv(path)


def _taylor_sample(data):
    return Sample(data, Design(wgt="w", stratum="stratum", psu="psu_id"))


def _rep_sample(data, df=None):
    rep = RepWeights(method="jackknife", prefix="rw", n_reps=N_REPS, df=df, rscales=RSCALES)
    return Sample(data, Design(wgt="w", stratum="stratum", psu="psu_id", rep_wgts=rep))


def _assert_values(est, exp_est, exp_se, exp_lci, exp_uci):
    p = est.estimates[0]
    assert p.est == pytest.approx(exp_est, rel=TOL)
    assert p.se == pytest.approx(exp_se, rel=TOL)
    assert p.lci == pytest.approx(exp_lci, rel=TOL)
    assert p.uci == pytest.approx(exp_uci, rel=TOL)


# ---------------------------------------------------------------------------
# Taylor — matches R's degf(design) and degf(subset(design))
# ---------------------------------------------------------------------------


def test_taylor_full_design_ci_matches_r(jkn_data):
    """Full design: df = 12 = sum_h (n_PSU_h - 1). R's degf(des)."""
    est = _taylor_sample(jkn_data).estimation.mean("y", method="taylor")
    _assert_values(est, 15.2657473567, 0.4173341861, 14.3564542778, 16.1750404356)


def test_taylor_domain_ci_uses_domain_df(jkn_data):
    """Domain: df = 7, not the full design's 12 — R's degf(subset(des, dom==1)).

    This is the regression guard for issue #3: a domain that drops whole PSUs
    must lose the df those PSUs carried.
    """
    est = _taylor_sample(jkn_data).estimation.mean("y", where=col("dom") == 1, method="taylor")
    _assert_values(est, 14.8967920329, 0.5903915609, 13.5007378301, 16.2928462357)


# ---------------------------------------------------------------------------
# Replication — df = n_reps - 1 by convention, domain or not
# ---------------------------------------------------------------------------


def test_replication_se_matches_r_full_design(jkn_data):
    """SE is R-exact; the CI uses df = 15 = n_reps - 1 (R's rank rule gives 12)."""
    est = _rep_sample(jkn_data).estimation.mean("y", method="replication")
    _assert_values(
        est,
        15.265747356692955,
        0.4173341860719779,  # == R's SE
        14.376220595443279,
        16.155274117942632,
    )


def test_replication_domain_se_matches_r_and_df_is_n_reps_minus_one(jkn_data):
    """Domain SE is R-exact (0.6111067974); the df stays 15 rather than R's 9.

    Pinned deliberately: the replicate df is a property of the weight set, not
    of the domain, so ``where=`` leaves it alone.
    """
    est = _rep_sample(jkn_data).estimation.mean("y", where=col("dom") == 1, method="replication")
    _assert_values(
        est,
        14.896792032894169,
        0.6111067973897552,  # == R's SE
        13.594248727309285,
        16.199335338479052,
    )


def test_replication_domain_total_uses_same_df(jkn_data):
    """Totals follow the same convention as means."""
    est = _rep_sample(jkn_data).estimation.total("y", where=col("dom") == 1, method="replication")
    _assert_values(
        est,
        10129.818582368034,
        1593.6649914950237,
        6733.002060471442,
        13526.635104264627,
    )


def test_user_supplied_rep_df_is_honoured(jkn_data):
    """An explicit RepWeights.df overrides n_reps - 1, on domains too.

    This is how a caller aligns svy with R's rank-based df when they want it:
    pass the df R would compute. Here df=9 reproduces R's domain CI exactly.
    """
    est = _rep_sample(jkn_data, df=9).estimation.mean(
        "y", where=col("dom") == 1, method="replication"
    )
    _assert_values(est, 14.8967920329, 0.6111067974, 13.5143724139, 16.2792116518)
